import dotEnv from "dotenv";
dotEnv.config();

export const { DATABASE_URL, NODE_ENV, PORT, REDIS_URL, JWT_SECRET, JWT_EXPIRES_IN, GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL, FRONTEND_URL, CLOUDINARY_API_SECRET, CLOUDINARY_API_KEY, CLOUDINARY_CLOUD_NAME,
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM } = process.env;
